name: cinetrack
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# ------------------- Application Dependencies -------------------
dependencies:
  flutter:
    sdk: flutter

  # --- UI & Utilities ---
  cupertino_icons: ^1.0.8
  lottie: ^3.1.2
  logger: ^2.4.0

  # --- State Management ---
  signals: ^5.2.0
  
  # --- Navigation ---
  auto_route: ^8.1.3

  # --- Dependency Injection ---
  get_it: ^7.7.0
  injectable: ^2.4.2

  # --- Networking ---
  dio: ^5.5.0+1

  # --- Data Models & Serialization ---
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.2

  # --- Firebase ---
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  flutter_dotenv: ^6.0.0

# ------------------- Development Dependencies -------------------
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # --- Code Generators ---
  build_runner: ^2.4.11
  auto_route_generator: ^8.0.1
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  freezed: ^2.5.2 # <-- FIX: Downgraded to resolve conflict

flutter:
  uses-material-design: true
  assets:
    - .env