// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnjh5rDlEKol3ELbtbw2lY73N3uBIKtFM',
    appId: '1:393713436453:web:93605f13b748e9c861fccc',
    messagingSenderId: '393713436453',
    projectId: 'cinetrack-81b88',
    authDomain: 'cinetrack-81b88.firebaseapp.com',
    storageBucket: 'cinetrack-81b88.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxFEzpt1_f9xPcU5v1Mii5Z4VhP94J3y0',
    appId: '1:393713436453:android:c034361ca580f33361fccc',
    messagingSenderId: '393713436453',
    projectId: 'cinetrack-81b88',
    storageBucket: 'cinetrack-81b88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAXBYlETX25EXyKINX4VZ_-_SGnVI7UNU',
    appId: '1:393713436453:ios:4a386e2c03ca5d3961fccc',
    messagingSenderId: '393713436453',
    projectId: 'cinetrack-81b88',
    storageBucket: 'cinetrack-81b88.firebasestorage.app',
    iosBundleId: 'com.example.cinetrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAXBYlETX25EXyKINX4VZ_-_SGnVI7UNU',
    appId: '1:393713436453:ios:4a386e2c03ca5d3961fccc',
    messagingSenderId: '393713436453',
    projectId: 'cinetrack-81b88',
    storageBucket: 'cinetrack-81b88.firebasestorage.app',
    iosBundleId: 'com.example.cinetrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnjh5rDlEKol3ELbtbw2lY73N3uBIKtFM',
    appId: '1:393713436453:web:7c16b7016e41642961fccc',
    messagingSenderId: '393713436453',
    projectId: 'cinetrack-81b88',
    authDomain: 'cinetrack-81b88.firebaseapp.com',
    storageBucket: 'cinetrack-81b88.firebasestorage.app',
  );
}
